import { Roboto } from "next/font/google";
import Header from "./components/header";
import "./globals.css";

import { AuthProvider } from "./context/AuthContext";
import { CartProvider } from "./context/CartContext";

const roboto = Roboto({
  variable: "--font-robot",
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin", "cyrillic", "cyrillic-ext"],
});

export const metadata = {
  title: 'gShop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (

      <html lang="en">
        <body
          className={`${roboto.variable} antialiased`}
        >
          <div className="w-full sm:w-5/6 md:4/6 m-auto p-2">
            <div className="flex flex-col mx-auto">
              <AuthProvider>
                <CartProvider>
                  <Header />
                  {children}
                </CartProvider>
              </AuthProvider>
            </div>
          </div>
        </body>
      </html>

  );
}
