import { Roboto } from "next/font/google";
import Header from "./components/header";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-robot",
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin", "cyrillic", "cyrillic-ext"],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} antialiased`}
      >
        <div className="w-full sm:w-5/6 md:4/6 m-auto p-2">
          <div className="flex flex-col mx-auto">
            <Header />
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
